#!/usr/bin/env python3
"""Makes Habnut's own furniture: classic pieces remade in Habnut colours, as
new items that exist nowhere else.

    make-exclusives.py <exclusives.json> <nitro root> <out.sql>

For each entry: a new artwork bundle (the original's, renamed and recoloured,
shadows left alone), its shop icon, a FurnitureData entry (kept in
gamedata/FurnitureData.habnut.json too, which build-gamedata.py merges back
in), and SQL for the emulator definition (copied from the original's
behaviour) and the shop. Needs Pillow. Safe to run again.
"""
import io
import json
import os
import struct
import sys
import zlib

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "scripts", "catalogue"))
import nitro  # noqa: E402

spec_path, root, out_sql = sys.argv[1:4]
spec = json.load(open(spec_path))
bundles = os.path.join(root, "bundled", "furniture")
icons = os.path.join(root, "c_images", "dcr", "hof_furni", "icons")
gamedata = os.path.join(root, "gamedata", "FurnitureData.json")
overlay = os.path.join(root, "gamedata", "FurnitureData.habnut.json")


def gradient(stops):
    """256-entry lookup from (position, (r, g, b)) stops."""
    lut = []
    for i in range(256):
        x = i / 255
        for (p0, c0), (p1, c1) in zip(stops, stops[1:]):
            if p0 <= x <= p1:
                t = (x - p0) / (p1 - p0) if p1 > p0 else 0
                lut.append(tuple(round(a + (b - a) * t) for a, b in zip(c0, c1)))
                break
    return lut


PALETTES = {name: gradient([(p, tuple(c)) for p, c in stops]) for name, stops in spec["palettes"].items()}


def recolour(img, lut, keep):
    """Maps every pixel's brightness onto the palette, except outlines and the boxes in keep."""
    src = img.convert("RGBA")
    out = src.copy()
    px, po = src.load(), out.load()
    w, h = src.size
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            if a == 0:
                continue
            lum = int(0.299 * r + 0.587 * g + 0.114 * b)
            if lum < 28:
                continue  # outlines stay crisp
            nr, ng, nb = lut[lum]
            po[x, y] = (nr, ng, nb, a)
    for (x0, y0, x1, y1) in keep:
        out.paste(src.crop((x0, y0, x1, y1)), (x0, y0))
    return out


def write_bundle(path, files):
    blob = bytearray(struct.pack(">H", len(files)))
    for name, data in files.items():
        packed = zlib.compress(data, 9)
        blob += struct.pack(">H", len(name)) + name.encode() + struct.pack(">I", len(packed)) + packed
    with open(path + ".part", "wb") as f:
        f.write(blob)
    os.replace(path + ".part", path)


def renamed(js, old, new):
    js = json.loads(json.dumps(js))
    js["name"] = new
    pre = old + "_"

    def fix(name):
        return new + "_" + name[len(pre):] if name.startswith(pre) else name

    assets = {}
    for k, v in js.get("assets", {}).items():
        if isinstance(v, dict) and "source" in v:
            v["source"] = fix(v["source"])
        assets[fix(k)] = v
    js["assets"] = assets
    sheet = js.get("spritesheet") or {}
    frames = {}
    for k, v in (sheet.get("frames") or {}).items():
        # frames are "<bundle>_<asset>": both halves carry the name
        rest = k[len(pre):] if k.startswith(pre) else k
        frames[new + "_" + fix(rest)] = v
    sheet["frames"] = frames
    if "meta" in sheet:
        sheet["meta"]["image"] = new + ".png"
    return js


def main():
    fd = json.load(open(gamedata))
    by_class = {t["classname"]: (section, t) for section in ("roomitemtypes", "wallitemtypes")
                for t in fd[section]["furnitype"]}
    extra = {"roomitemtypes": [], "wallitemtypes": []}
    sql = ["-- Habnut exclusives. Generated by make-exclusives.py."]
    page = spec["page"]
    sql.append(
        "INSERT INTO catalog_pages (id, parent_id, caption_save, caption, page_layout, icon_color, icon_image, min_rank,"
        " order_num, visible, enabled, club_only, vip_only, page_headline, page_teaser, page_special, page_text1,"
        " page_text2, page_text_details, page_text_teaser, room_id, includes, catalog_mode)"
        f" VALUES ({page['id']}, {page['parent']}, 'habnut_exclusives', {json.dumps(page['caption'])}, 'default_3x3', 1,"
        f" {page['icon']}, 1, -10, '1', '1', '0', '0', {json.dumps(page.get('headline', ''))}, '', '',"
        f" {json.dumps(page['text'])}, '', '', '', 0, '', 'NORMAL')"
        " ON DUPLICATE KEY UPDATE caption=VALUES(caption), page_text1=VALUES(page_text1), order_num=-10,"
        " page_headline=VALUES(page_headline);")

    for n, item in enumerate(spec["items"]):
        base, new, fid = item["base"], item["classname"], item["id"]
        section, t = by_class[base]
        files = nitro.read(os.path.join(bundles, base + ".nitro"))
        js = json.loads(next(v for k, v in files.items() if k.endswith(".json")))
        sheet = Image.open(io.BytesIO(next(v for k, v in files.items() if k.endswith(".png"))))
        frames = (js.get("spritesheet") or {}).get("frames") or {}
        shadows = [(f["frame"]["x"], f["frame"]["y"], f["frame"]["x"] + f["frame"]["w"], f["frame"]["y"] + f["frame"]["h"])
                   for k, f in frames.items() if "_sd_" in k]
        coloured = recolour(sheet, PALETTES[item.get("palette", "gold")], shadows)
        png = io.BytesIO()
        coloured.save(png, "PNG", optimize=True)
        new_js = renamed(js, base, new)
        write_bundle(os.path.join(bundles, new + ".nitro"),
                     {new + ".json": json.dumps(new_js, separators=(",", ":")).encode(), new + ".png": png.getvalue()})

        icon_key = next((k for k in new_js["spritesheet"]["frames"] if k.endswith("_icon_a")), None)
        if icon_key:
            f = new_js["spritesheet"]["frames"][icon_key]["frame"]
            coloured.crop((f["x"], f["y"], f["x"] + f["w"], f["y"] + f["h"])).save(os.path.join(icons, new + "_icon.png"))

        entry = dict(t)
        entry.update({"id": fid, "classname": new, "name": item["name"], "description": item["description"],
                      "furniline": "habnut_exclusives", "revision": 1, "offerid": -1, "rentofferid": -1,
                      "buyout": False, "rentbuyout": False, "bc": False, "excludeddynamic": False, "rare": True})
        extra[section].append(entry)

        kind = "s" if section == "roomitemtypes" else "i"
        price = item.get("diamonds", 15)
        ltd = item.get("limited", 0)
        sql.append(
            "INSERT INTO items_base (sprite_id, public_name, item_name, type, width, length, stack_height, allow_stack,"
            " allow_sit, allow_lay, allow_walk, allow_gift, allow_trade, allow_recycle, allow_marketplace_sell,"
            " allow_inventory_stack, interaction_type, interaction_modes_count, vending_ids, multiheight, customparams,"
            " effect_id_male, effect_id_female, clothing_on_walk)"
            f" SELECT {fid}, {json.dumps(item['name'][:56])}, '{new}', type, width, length, stack_height, allow_stack, allow_sit,"
            " allow_lay, allow_walk, 1, 1, 0, 1, allow_inventory_stack, interaction_type, interaction_modes_count, vending_ids,"
            " multiheight, customparams, effect_id_male, effect_id_female, clothing_on_walk"
            f" FROM items_base WHERE item_name = '{base}' AND NOT EXISTS (SELECT 1 FROM items_base WHERE item_name = '{new}') LIMIT 1;")
        sql.append(f"UPDATE items_base SET sprite_id = {fid}, public_name = {json.dumps(item['name'][:56])} WHERE item_name = '{new}';")
        sql.append(
            "INSERT INTO catalog_items (item_ids, page_id, catalog_name, cost_credits, cost_points, points_type, amount,"
            " limited_stack, limited_sells, order_number, offer_id, song_id, extradata, have_offer, club_only)"
            f" SELECT b.id, {page['id']}, '{new}', 0, {price}, 5, 1, {ltd}, 0, {n + 1}, -1, 0, '', '{0 if ltd else 1}', '0'"
            f" FROM items_base b WHERE b.item_name = '{new}'"
            f" AND NOT EXISTS (SELECT 1 FROM catalog_items WHERE catalog_name = '{new}') LIMIT 1;")
        print(f"  {new}: {item['name']}")

    # Merge into the live furniture data, replacing earlier copies of ours.
    ours = {e["classname"] for s in extra.values() for e in s}
    for section in ("roomitemtypes", "wallitemtypes"):
        fd[section]["furnitype"] = [t for t in fd[section]["furnitype"] if t["classname"] not in ours] + extra[section]
    json.dump(fd, open(gamedata + ".part", "w"), ensure_ascii=False, separators=(",", ":"))
    os.replace(gamedata + ".part", gamedata)
    json.dump(extra, open(overlay, "w"), ensure_ascii=False, indent=1)
    open(out_sql, "w").write("\n".join(sql) + "\n")
    print(f"{len(ours)} exclusives made")


if __name__ == "__main__":
    main()
