package dev

import (
	"fmt"
	"os"
	"strings"
	"text/template"
)

// The stack a local hotel runs as.
//
// Deliberately not the production stack. There is no TLS, no Loki log driver,
// no secrets files, no resource limits and no restart policy — a local hotel
// that restarts itself after you stopped it is a nuisance, not a feature.
// Every published port is bound to 127.0.0.1 so nothing on the network can
// reach a hotel somebody started to have a look at.
const composeTemplate = `# Habnut — local hotel
#
# Generated by 'habnutctl dev up'. Edit it if you like; 'habnutctl dev up'
# will not overwrite your changes unless you pass --recreate.
#
# Everything here is bound to 127.0.0.1. Nothing is reachable from the network.

name: {{.Project}}

services:
  db:
    image: mariadb:10.11
    command: ["--max_allowed_packet=64M"]
    environment:
      MARIADB_ROOT_PASSWORD: habnut
      MARIADB_DATABASE: habnut
      MARIADB_USER: habnut
      MARIADB_PASSWORD: habnut
    ports:
      - "127.0.0.1:{{.DBPort}}:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 30s

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--save", "", "--appendonly", "no"]
    ports:
      - "127.0.0.1:{{.RedisPort}}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  # Catches every message the hotel sends, so registration and password resets
  # can be followed through without a mail server. Nothing leaves the machine.
  mail:
    image: axllent/mailpit:latest
    ports:
      - "127.0.0.1:{{.MailPort}}:8025"
    environment:
      MP_MAX_MESSAGES: "500"
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"

  emulator:
    image: eclipse-temurin:21-jre
    working_dir: /app
    command: ["java", "-jar", "/app/habnut-emulator.jar"]
    environment:
      DB_URL: "jdbc:mariadb://db:3306/habnut?useUnicode=true&characterEncoding=utf8"
      DB_USERNAME: habnut
      DB_PASSWORD: habnut
      REDIS_HOST: redis
      REDIS_PORT: "6379"
      WS_PORT: "{{.WSPort}}"
      HEALTH_PORT: "{{.APIPort}}"
      METRICS_PORT: "{{.MetricsPort}}"
      WORLD_ID: "{{.WorldID}}"
      DEV_MODE: "true"
      SESSION_TICKET_TTL_SECONDS: "300"
    volumes:
      - ./emulator:/app:ro
      - ./logs:/var/log/habnut
    # Checked through bash's own TCP support rather than curl, which the
    # Temurin images do not carry. Without this a hotel that fell over on
    # start-up still reported as running, and 'dev up' would hand somebody a
    # working website attached to nothing.
    healthcheck:
      test: ["CMD", "bash", "-c", ":< /dev/tcp/127.0.0.1/{{.APIPort}}"]
      interval: 5s
      timeout: 3s
      retries: 24
      start_period: 20s
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Built rather than pulled, because the official PHP images do not carry
  # pdo_mysql and compiling it needs build tools they drop from the final
  # image. Doing that at container start would mean installing a compiler on
  # every 'dev up'; doing it here happens once and is then cached.
  cms:
    build:
      context: .
      dockerfile: Dockerfile.cms
    working_dir: /var/www/cms
    command: ["sh", "/var/www/cms/dev-entrypoint.sh"]
    environment:
      APP_ENV: local
      APP_DEBUG: "true"
    volumes:
      - ./cms:/var/www/cms
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    image: nginx:1.27-alpine
    ports:
      - "127.0.0.1:{{.HTTPPort}}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./cms:/var/www/cms:ro
      - ./client:/var/www/client:ro
      - ./assets:/var/www/assets:ro
    depends_on:
      - cms
      - emulator

volumes:
  db_data:
`

// The web server for a local hotel.
//
// The same shape as the real one — the site at /, the game client at /client/,
// the socket at /ws — so what is tried here is what runs on a server. What is
// gone is everything that needs a domain: no TLS, no redirect to HTTPS, no
// HSTS, and a content policy that allows the websocket on a plain-HTTP origin.
const nginxTemplate = `# Habnut — local hotel
#
# The same layout as a real install: the website at /, the game client at
# /client/, the hotel's socket at /ws. Without the TLS, since there is no
# domain and no certificate on a machine talking to itself.

server {
    listen 80 default_server;
    server_name localhost 127.0.0.1;

    root /var/www/cms/public;
    index index.php;

    client_max_body_size 50M;

    # Enough of a content policy to catch a mistake, without the parts that
    # assume a certificate.
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    location /ws {
        proxy_pass http://emulator:{{.WSPort}};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    location /emulator/ {
        proxy_pass http://emulator:{{.APIPort}}/;
        proxy_set_header Host $host;
    }

    # Its own index: the server's is index.php, so without this the bare
    # /client/ the website sends a signed-in player to was a forbidden
    # directory listing rather than the game.
    location /client/ {
        alias /var/www/client/;
        index index.html;
        try_files $uri $uri/ /client/index.html;
    }

    # Content-hashed, so they could be cached forever — but a local hotel is
    # rebuilt constantly and a cached bundle is a confusing way to lose an
    # afternoon, so they are not.
    location /client/assets/ {
        alias /var/www/client/assets/;
        try_files $uri =404;
        add_header Cache-Control "no-store" always;
    }

    # The artwork, as the game client asks for it: /assets/<era>/...
    #
    # Empty until a pack is installed with 'habnutctl swf install --local',
    # and the client draws plain shapes until then. Not cached, because
    # reinstalling a pack and looking again is the whole point of having the
    # hotel on your own machine.
    location /assets/ {
        alias /var/www/assets/;
        try_files $uri =404;
        add_header Cache-Control "no-store" always;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass cms:9000;
        fastcgi_index index.php;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout 120s;
    }

    location ~ /\. {
        deny all;
    }
}
`

// What the website is told about where everything is.
//
// APP_DEBUG is on and the log level is debug, because the whole point of a
// local hotel is to see what went wrong.
const cmsEnvTemplate = `APP_NAME="Habnut (local)"
APP_ENV=local
APP_KEY={{.AppKey}}
APP_DEBUG=true
APP_URL={{.URL}}

LOG_CHANNEL=stack
LOG_LEVEL=debug

DB_CONNECTION=mysql
DB_HOST=db
DB_PORT=3306
DB_DATABASE=habnut
DB_USERNAME=habnut
DB_PASSWORD=habnut

BROADCAST_DRIVER=redis
CACHE_DRIVER=redis
FILESYSTEM_DISK=local
QUEUE_CONNECTION=sync
SESSION_DRIVER=redis
SESSION_LIFETIME=120

REDIS_CLIENT=predis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=null

MAIL_MAILER=smtp
MAIL_HOST=mail
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=hotel@habnut.local
MAIL_FROM_NAME="${APP_NAME}"

EMULATOR_HOST=emulator
EMULATOR_PORT={{.APIPort}}

# The game client is served from this same host, under /client/.
CLIENT_URL=/client/

# Which world this hotel puts a player in. The world travels on the handover
# ticket, so this is what --rp changes: without it the stack would run the
# roleplay city and the site would still send everybody to the hotel.
HABNUT_WORLD={{.WorldID}}

# No imager runs in a local stack, and there is no asset pack for one to draw
# from, so this is left empty and the site shows a monogram instead of asking
# for pictures nothing is serving. Install a pack with 'habnutctl swf install',
# run 'habnutctl imager', and set this to where it is listening.
IMAGER_URL=

HABNUT_TICKET_TTL_MINUTES=5
`

// The website's image.
//
// The official PHP images ship the extension sources but not the tools to
// build them: $PHPIZE_DEPS is installed for the build and dropped from the
// final image. An entrypoint that ran docker-php-ext-install would therefore
// need to install a compiler every time a container started — slow, and it
// fails outright on a machine with no network.
//
// pdo_mysql is what the website talks to the database with. bcmath and pcntl
// are declared requirements of packages it ships with. opcache is here because
// without it every request recompiles every file, which on a bind-mounted
// source tree is the difference between a page in 80ms and a page in a second.
const cmsDockerfile = `# Habnut — the website, locally
#
# Generated by 'habnutctl dev up'. Built once and cached; 'dev up' does not
# rebuild it unless you pass --recreate or the file changes.

FROM php:8.3-fpm-alpine

RUN set -eux; \
    apk add --no-cache --virtual .build-deps $PHPIZE_DEPS; \
    docker-php-ext-install -j"$(nproc)" pdo_mysql bcmath pcntl opcache; \
    apk del .build-deps

# Development settings: see the error, do not cache the templates.
RUN { \
      echo 'opcache.enable=1'; \
      echo 'opcache.validate_timestamps=1'; \
      echo 'opcache.revalidate_freq=0'; \
      echo 'display_errors=On'; \
      echo 'display_startup_errors=On'; \
      echo 'error_reporting=E_ALL'; \
      echo 'memory_limit=512M'; \
      echo 'upload_max_filesize=50M'; \
      echo 'post_max_size=50M'; \
    } > /usr/local/etc/php/conf.d/habnut-dev.ini

WORKDIR /var/www/cms
`

// The website's container brings itself up: it waits for the database, applies
// its migrations and serves. Written as a script rather than a chain of
// compose directives so what happens is readable and so a failure says which
// step failed.
const cmsEntrypoint = `#!/bin/sh
# Habnut — local website container
#
# Generated by 'habnutctl dev up'. The extensions are already in the image;
# this only waits for the database, brings the schema up to date and serves.
set -e

echo "[cms] waiting for the database..."
tries=0
until php -r 'new PDO("mysql:host=db;port=3306;dbname=habnut", "habnut", "habnut");' 2>/dev/null; do
  tries=$((tries + 1))
  if [ "$tries" -gt 60 ]; then
    echo "[cms] the database never came up" >&2
    exit 1
  fi
  sleep 2
done

# Every artisan command runs as www-data, the user php-fpm serves as. Run as
# root, the first thing one logged created laravel.log owned by root, and from
# then on php-fpm could not write its own log and every page was a 500.
artisan() { su -s /bin/sh -c "php artisan $*" www-data; }

echo "[cms] applying website migrations..."
artisan migrate --force --no-interaction

echo "[cms] clearing caches..."
artisan config:clear >/dev/null 2>&1 || true
artisan route:clear >/dev/null 2>&1 || true
artisan view:clear >/dev/null 2>&1 || true

echo "[cms] ready"
exec php-fpm
`

// composeData is what the templates are filled from.
type composeData struct {
	*Env
	Project     string
	MetricsPort int
	WorldID     string
	AppKey      string
	URL         string
}

func (e *Env) templateData(appKey string) composeData {
	world := "classic"
	if e.RP {
		world = "nutropolis"
	}
	return composeData{
		Env:         e,
		Project:     e.Project(),
		MetricsPort: e.APIPort + 1,
		WorldID:     world,
		AppKey:      appKey,
		URL:         e.URL(),
	}
}

// WriteStack writes the compose file, the web server config, the website's
// settings and its entrypoint.
//
// An existing file is left alone unless overwrite is set, so somebody who has
// changed the compose file to add a service of their own does not lose it to
// the next `habnutctl dev up`.
func (e *Env) WriteStack(appKey string, overwrite bool) error {
	data := e.templateData(appKey)

	files := []struct {
		path     string
		template string
		mode     os.FileMode
	}{
		{e.ComposeFile(), composeTemplate, 0o644},
		{e.NginxConf(), nginxTemplate, 0o644},
		{e.CMSDockerfile(), cmsDockerfile, 0o644},
		// Readable by everyone, not just its owner. The website reads it
		// inside its container as www-data, a different user from the one who
		// ran 'dev up', so owner-only meant the website could never read its
		// own settings: it fell back to 127.0.0.1 and failed every request.
		// What it holds is local: the dev database's password and a key made on
		// this machine, for a hotel that listens on nothing but 127.0.0.1.
		{e.CMSDir() + "/.env", cmsEnvTemplate, 0o644},
		{e.CMSDir() + "/dev-entrypoint.sh", cmsEntrypoint, 0o755},
	}

	for _, f := range files {
		if !overwrite {
			if _, err := os.Stat(f.path); err == nil {
				// Kept as it is, but with the permissions it needs, so a hotel
				// made before the .env above was readable mends itself.
				if err := os.Chmod(f.path, f.mode); err != nil {
					return fmt.Errorf("could not set permissions on %s: %w", f.path, err)
				}
				continue
			}
		}
		rendered, err := render(f.template, data)
		if err != nil {
			return fmt.Errorf("%s: %w", f.path, err)
		}
		if err := os.WriteFile(f.path, []byte(rendered), f.mode); err != nil {
			return fmt.Errorf("could not write %s: %w", f.path, err)
		}
	}

	return nil
}

func render(tmpl string, data composeData) (string, error) {
	t, err := template.New("dev").Parse(tmpl)
	if err != nil {
		return "", err
	}
	var out strings.Builder
	if err := t.Execute(&out, data); err != nil {
		return "", err
	}
	return out.String(), nil
}
