#!/usr/bin/env python3
"""Habnut's quests: names, texts, pictures and the new campaigns.

    make-quests.py <quests.json> <nitro root> <out.sql>

Writes the quest rows for new campaigns (existing ones keep their goals and
rewards), every quest's name, description, hint and completion line into
ExternalTexts.habnut.json and the live ExternalTexts.json, and a picture for
each quest and campaign in c_images/questing, drawn like Habnut's badges.
Completion badges are drawn and named too. Needs Pillow. Safe to run again.
"""
import importlib.util
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
spec_path, root, out_sql = sys.argv[1:4]
spec = json.load(open(spec_path))

loader = importlib.util.spec_from_file_location("badges", os.path.join(HERE, "..", "badges", "make-badges.py"))
badges = importlib.util.module_from_spec(loader)
loader.loader.exec_module(badges)

icons = os.path.join(root, "c_images", "dcr", "hof_furni", "icons")
questing = os.path.join(root, "c_images", "questing")
album = os.path.join(root, "c_images", "album1584")
os.makedirs(questing, exist_ok=True)


def icon_path(name):
    for candidate in (name, "rare_globe"):
        path = os.path.join(icons, candidate + "_icon.png")
        if os.path.exists(path):
            return path
    return None


def q(s):
    return "'" + str(s).replace("\\", "\\\\").replace("'", "''") + "'"


def main():
    texts, sql = {}, ["-- Habnut quests. Generated by make-quests.py."]
    for camp in spec["campaigns"]:
        code, colour = camp["code"], camp["colour"]
        texts[f"quests.{code}.name"] = camp["name"]
        texts[f"quests.{code}"] = camp["name"]
        badges.badge(colour, icon_path(camp["icon"])).save(os.path.join(questing, f"{code}.png"))
        for n, quest in enumerate(camp["quests"]):
            qc = quest["code"]
            for field in ("name", "desc", "hint", "completed"):
                texts[f"quests.{code}.{qc}.{field}"] = quest[field]
            picture = badges.badge(colour, icon_path(quest["icon"]))
            for version in ("1", ""):
                picture.save(os.path.join(questing, f"{code}_{qc}{version}.png".lower()))
            if quest.get("badge"):
                badges.to_gif(badges.badge(colour, icon_path(camp["icon"]), ring=[60, 40, 0]),
                              os.path.join(album, quest["badge"] + ".gif"))
                texts[f"badge_name_{quest['badge']}"] = camp["name"]
                texts[f"badge_desc_{quest['badge']}"] = f"Completed the {camp['name']} quests."
            if "goal" not in quest:
                continue  # an existing quest: texts and picture only
            sql.append(
                "INSERT INTO quests (campaign_code, code, chain_code, sort_order, goal_type, goal_data, goal_count, reward_type,"
                " reward_amount, reward_badge, easy, daily, seasonal_seconds, wait_seconds, catalog_page_name, image_version, enabled)"
                f" SELECT {q(code)}, {q(qc)}, '', {n + 1}, {q(quest['goal'])}, '', {quest['count']}, {quest['reward_type']},"
                f" {quest['reward']}, {q(quest.get('badge', ''))}, {quest.get('easy', 1)}, {quest.get('daily', 0)}, 0, 0, '', '1', 1"
                f" FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM quests WHERE code = {q(qc)});")

    overlay_path = os.path.join(root, "gamedata", "ExternalTexts.habnut.json")
    overlay = json.load(open(overlay_path)) if os.path.exists(overlay_path) else {}
    overlay.update(texts)
    json.dump(overlay, open(overlay_path, "w"), ensure_ascii=False, indent=1)
    live_path = os.path.join(root, "gamedata", "ExternalTexts.json")
    live = json.load(open(live_path))
    live.update(overlay)
    json.dump(live, open(live_path + ".part", "w"), ensure_ascii=False, separators=(",", ":"))
    os.replace(live_path + ".part", live_path)
    open(out_sql, "w").write("\n".join(sql) + "\n")
    print(f"{len(texts)} texts, {len(sql) - 1} new quests")


if __name__ == "__main__":
    main()
