flyway.locations=classpath:db/migration
flyway.baselineOnMigrate=false
flyway.validateOnMigrate=true
flyway.outOfOrder=false
flyway.cleanDisabled=true
flyway.encoding=UTF-8
flyway.placeholderReplacement=false
