#!/usr/bin/env python3
"""Draws a Habnut header for every shop page, replacing the original artwork
(some of which spelled out the hotel-of-origin's name).

    make-headers.py <pages.json> <fonts dir> <nitro root> <out.sql>

Each header is 284x45 like the originals: a band in the section's colour
with a few of the page's own furniture on the right. No words: the client
writes the page title over it. Written as catalogue/habnut_header_<page>.gif. Needs Pillow.
"""
import json
import os
import sys

from PIL import Image, ImageDraw, ImageFont

pages_path, fonts, root, out_sql = sys.argv[1:5]
pages = json.load(open(pages_path))
icons = os.path.join(root, "c_images", "dcr", "hof_furni", "icons")
target = os.path.join(root, "c_images", "catalogue")

SECTIONS = {  # root page -> (top colour, bottom colour)
    2: ((255, 176, 60), (214, 104, 10)),     # Furni
    3: ((240, 120, 170), (178, 50, 110)),    # Clothing
    4: ((120, 200, 110), (50, 130, 60)),     # Pets
    5: ((100, 170, 230), (30, 100, 170)),    # Building
    7: ((150, 150, 160), (80, 80, 92)),      # Staff
    1111: ((170, 120, 220), (100, 60, 160)), # Nuticons
}
GOLD = ((255, 222, 90), (226, 150, 8))
W, H = 284, 45
title_font = ImageFont.truetype(os.path.join(fonts, "LilitaOne-Regular.ttf"), 20)


def band(top, bottom):
    img = Image.new("RGBA", (W, H))
    d = ImageDraw.Draw(img)
    for y in range(H):
        t = y / (H - 1)
        d.line([(0, y), (W, y)], fill=tuple(int(a + (b - a) * t) for a, b in zip(top, bottom)) + (255,))
    # a few soft diagonal stripes for texture, blended over the colour
    stripes = Image.new("RGBA", (W, H), (0, 0, 0, 0))
    sd = ImageDraw.Draw(stripes)
    for x in range(-H, W, 22):
        sd.line([(x, H), (x + H, 0)], fill=(255, 255, 255, 26), width=7)
    sd.line([(0, 0), (W, 0)], fill=(255, 255, 255, 110))
    sd.line([(0, H - 1), (W, H - 1)], fill=(0, 0, 0, 90))
    img.alpha_composite(stripes)
    return img


def icon(name):
    base, _, colour = name.partition("*")
    path = os.path.join(icons, f"{base}{'_' + colour if colour else ''}_icon.png")
    if not os.path.exists(path):
        path = os.path.join(icons, f"{base}_icon.png")
    if not os.path.exists(path):
        return None
    img = Image.open(path).convert("RGBA")
    return img if img.getbbox() else None


def header(page):
    top, bottom = GOLD if "Exclusive" in page["caption"] else SECTIONS.get(page["root"], SECTIONS[2])
    img = band(top, bottom)
    # the page's own furniture, right to left, biggest first
    pics = [p for p in (icon(n) for n in page["items"]) if p is not None]
    pics.sort(key=lambda p: -(p.width * p.height))
    x = W - 6
    for pic in pics[:5]:
        pic.thumbnail((40, 38), Image.NEAREST)
        x -= pic.width
        img.alpha_composite(pic, (x, H - 4 - pic.height))
        x -= 4
    return img


def to_gif(img, path):
    flat = Image.new("RGB", img.size, (0, 0, 0))
    flat.paste(img.convert("RGB"), mask=img.getchannel("A"))
    flat.quantize(colors=255, method=Image.Quantize.MEDIANCUT).save(path)


def borrow_pictures():
    """Section pages with no items of their own show their sub-pages' furniture."""
    kids = {}
    for page in pages:
        kids.setdefault(page["parent"], []).append(page)

    def collect(page, depth=0):
        found = list(page["items"])
        for kid in kids.get(page["id"], []):
            if len(found) >= 12 or depth > 3:
                break
            found += collect(kid, depth + 1)[:4]
        return found

    for page in pages:
        if not page["items"]:
            page["items"] = collect(page)[:12]


def main():
    borrow_pictures()
    sql = ["-- Habnut shop headers. Generated by make-headers.py."]
    for page in pages:
        name = f"habnut_header_{page['id']}"
        to_gif(header(page), os.path.join(target, name + ".gif"))
        sql.append(f"UPDATE catalog_pages SET page_headline = '{name}' WHERE id = {page['id']};")
    open(out_sql, "w").write("\n".join(sql) + "\n")
    print(f"{len(pages)} headers drawn")


if __name__ == "__main__":
    main()
